apiVersion: v1
kind: Pod
metadata:
  name: ingress-test
  namespace: shopsphere
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: ingress-test
      image: curlimages/curl:8.10.1
      command:
        - sleep
        - "3600"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
