apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopsphere-backend
  namespace: shopsphere
spec:
  replicas: 2

  selector:
    matchLabels:
      app: shopsphere-backend

  template:
    metadata:
      labels:
        app: shopsphere-backend

    spec:
      automountServiceAccountToken: false

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      volumes:
        - name: backend-db
          persistentVolumeClaim:
            claimName: shopsphere-backend-db

      containers:
        - name: shopsphere-backend

          image: sameer340314/shopsphere-backend:d83275c

          imagePullPolicy: Always

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 8000

          volumeMounts:
            - name: backend-db
              mountPath: /app/shopsphere.db
              subPath: shopsphere.db

          envFrom:
            - configMapRef:
                name: shopsphere-config
            - secretRef:
                name: shopsphere-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
