apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopsphere-frontend
  namespace: shopsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopsphere-frontend
  template:
    metadata:
      labels:
        app: shopsphere-frontend
    spec:
      containers:
        - name: shopsphere-frontend
          image: shopsphere-frontend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20